"""PaedDeadSpace v1.0.0 scientific core.

This package is educational/exploratory software, not patient-specific
clinical decision support.
"""

__version__ = "1.0.0"

from .core import (
    alveolar_minute_ventilation_ml_min,
    alveolar_tidal_volume_ml,
    apparatus_dead_space_percent_vt,
    apparatus_stack_dead_space_ml,
    baseline_calibrated_paco2_mechanistic_mmHg,
    calculate_tidal_volume_ml,
    calculate_ventilation,
    dead_space_fraction,
    numa_fletcher_composite_reference,
    numa_total_anatomic_dead_space_reference,
    patient_dead_space_excluding_apparatus_ml,
    relative_co2_burden,
    rr_required_to_preserve_alveolar_ventilation,
    total_dead_space_ml,
    vco2_lindahl_bja_1989_ml_min,
    vco2_lindahl_cja_1989_ml_min,
    vco2_pearsall_brody_benchmark_ml_min,
    vt_to_apparatus_dead_space_ratio,
)
from .models import (
    ApparatusComponent,
    CohortReferenceInterval,
    NumaFletcherCompositeComponents,
    NumaFletcherCompositeReference,
    InputValidationError,
    NonPhysicalStateError,
    NumaTotalAnatomicDeadSpaceReference,
    PaedDeadSpaceError,
    PatientDeadSpaceModel,
    PearsallBenchmarkPatientDeadSpace,
    SourceDomainWarning,
    UserDefinedPatientVdVt,
    VentilationInputs,
    VentilationState,
    WILLIAMS_TERM_INFANT_REFERENCE_PROFILE,
    WilliamsTermInfantReferenceProfile,
)
from .provenance import (
    BENCHMARK_EQUATIONS,
    EMPIRICAL_EQUATIONS,
    FLETCHER_ALVEOLAR_DEAD_SPACE_FRACTION,
    HEALTHY_INTUBATED_COMPOSITE_REFERENCE_EQUATION,
    MODEL_CONSTRUCTION_EQUATIONS,
    NUMA_INTRATHORACIC_DEAD_SPACE_ML_KG,
    SCIENTIFIC_EQUATIONS,
    VT_PRESETS_ML_KG,
    WILLIAMS_TERM_CONTROL_2022,
    EquationProvenance,
    EvidenceSource,
    NamedConstant,
    ParameterClassification,
    Provenance,
)

__all__ = [
    "ApparatusComponent",
    "BENCHMARK_EQUATIONS",
    "CohortReferenceInterval",
    "EMPIRICAL_EQUATIONS",
    "EquationProvenance",
    "EvidenceSource",
    "FLETCHER_ALVEOLAR_DEAD_SPACE_FRACTION",
    "HEALTHY_INTUBATED_COMPOSITE_REFERENCE_EQUATION",
    "NumaFletcherCompositeComponents",
    "NumaFletcherCompositeReference",
    "InputValidationError",
    "MODEL_CONSTRUCTION_EQUATIONS",
    "NUMA_INTRATHORACIC_DEAD_SPACE_ML_KG",
    "NamedConstant",
    "NonPhysicalStateError",
    "NumaTotalAnatomicDeadSpaceReference",
    "PaedDeadSpaceError",
    "ParameterClassification",
    "PatientDeadSpaceModel",
    "PearsallBenchmarkPatientDeadSpace",
    "Provenance",
    "SCIENTIFIC_EQUATIONS",
    "SourceDomainWarning",
    "UserDefinedPatientVdVt",
    "VT_PRESETS_ML_KG",
    "VentilationInputs",
    "VentilationState",
    "WILLIAMS_TERM_CONTROL_2022",
    "WILLIAMS_TERM_INFANT_REFERENCE_PROFILE",
    "WilliamsTermInfantReferenceProfile",
    "alveolar_minute_ventilation_ml_min",
    "alveolar_tidal_volume_ml",
    "apparatus_dead_space_percent_vt",
    "apparatus_stack_dead_space_ml",
    "baseline_calibrated_paco2_mechanistic_mmHg",
    "calculate_tidal_volume_ml",
    "calculate_ventilation",
    "dead_space_fraction",
    "numa_fletcher_composite_reference",
    "numa_total_anatomic_dead_space_reference",
    "patient_dead_space_excluding_apparatus_ml",
    "relative_co2_burden",
    "rr_required_to_preserve_alveolar_ventilation",
    "total_dead_space_ml",
    "vco2_lindahl_bja_1989_ml_min",
    "vco2_lindahl_cja_1989_ml_min",
    "vco2_pearsall_brody_benchmark_ml_min",
    "vt_to_apparatus_dead_space_ratio",
]
